build: off

clone_folder: c:\gopath\src\github.com\gomods\athens

environment:
  GOPATH: c:\gopath
  GO111MODULE: on
  GOPROXY: https://proxy.golang.org
  SKIP_UNTIL_113: true

stack: go 1.14

test_script:
  - go version
  - go test ./...

